include		./Makefile.config
include		./Makefile.macros

INSTALLDIR32	= /kernel/drv
BINDIR32	= sparc

CFLAGS32	= ${OFLAGS_GCC} ${KFLAGS_GCC} ${AFLAGS_GCC_SPARC}  \
		  ${DFLAGS} ${CFGFLAGS} ${VFLAGS}

CC	= gcc
LD	= /usr/ccs/bin/ld

all:	${BINDIR32}/${DRV}

install:	install32 /etc/system.no${DRV}

uninstall:	uninstall32

clean:	clean32

include ./Makefile.common
