#
# Common configuration infomations for all platforms
#
DRV	= alta
VERSION	= 1.0.13
PKGREV	=
DISTDIR	= ../${DRV}-${VERSION}${PKGREV}

DFLAGS	= -UDEBUG -DDEBUG_LEVEL=0 -UGEM_DEBUG_LEVEL
#
# Don't use MAP_MEM because it doesn't work for DFE-580
#
CFGFLAGS = -UUSE_FRAMEID -UMAP_MEM -DGEM_CONFIG_POLLING
