#
# Common configuration infomations for all platforms
#
DRV	= ife
VERSION	= 0.9.0
PKGREV	=
DISTDIR	= ../${DRV}-${VERSION}${PKGREV}

DFLAGS		= -DDEBUG -DDEBUG_LEVEL=0 -UGEM_DEBUG_LEVEL -UTDU_TEST
CFGFLAGS	= -DEXTEND_TCB -DMAP_MEM
