#
# Common configuration infomations for all platforms
#
DRV	= urf
include version

KFLAGS_SUNCC += -erroff=E_STATEMENT_NOT_REACHED,E_INTEGER_OVERFLOW_DETECTED

DFLAGS	= -DDEBUG -DDEBUG_LEVEL=0 -DUSBGEM_DEBUG_LEVEL=0 \
	  -DCONFIG_TX_LIMITER

CFGFLAGS = -UUSBGEM_CONFIG_GLDv3 \
	   -Unotdef -UNEVER -DUSBGEM_GCC_RUNTIME \
	   -USANITY -UMODULE

LDFLAGS	+= -dy -N misc/gld -N misc/usba
